//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVeTau.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BanVeTau.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1433781547_point_arrow_point {
            get {
                object obj = ResourceManager.GetObject("1433781547_point_arrow_point", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1433782846_8 {
            get {
                object obj = ResourceManager.GetObject("1433782846_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1433783121_train {
            get {
                object obj = ResourceManager.GetObject("1433783121_train", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1433797291_Plus {
            get {
                object obj = ResourceManager.GetObject("1433797291_Plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1434476717_tickets {
            get {
                object obj = ResourceManager.GetObject("1434476717_tickets", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1434477060_ticket {
            get {
                object obj = ResourceManager.GetObject("1434477060_ticket", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn ghế ngồi.
        /// </summary>
        internal static string BanChuaChonGheDeDatVe {
            get {
                return ResourceManager.GetString("BanChuaChonGheDeDatVe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bed0 {
            get {
                object obj = ResourceManager.GetObject("bed0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bed1 {
            get {
                object obj = ResourceManager.GetObject("bed1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật .
        /// </summary>
        internal static string CapNhat {
            get {
                return ResourceManager.GetString("CapNhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chair0 {
            get {
                object obj = ResourceManager.GetObject("chair0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chair1 {
            get {
                object obj = ResourceManager.GetObject("chair1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập đủ các trường bắt buộc .
        /// </summary>
        internal static string ChuaNhapDuCacTruongBatBuoc {
            get {
                return ResourceManager.GetString("ChuaNhapDuCacTruongBatBuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap create_ticket_icon16 {
            get {
                object obj = ResourceManager.GetObject("create-ticket-icon16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  đã tồn tại .
        /// </summary>
        internal static string daTonTai {
            get {
                return ResourceManager.GetString("daTonTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  đối tượng .
        /// </summary>
        internal static string doiTuong {
            get {
                return ResourceManager.GetString("doiTuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng đã tồn tại.
        /// </summary>
        internal static string DoiTuongDaTonTai {
            get {
                return ResourceManager.GetString("DoiTuongDaTonTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị nhập không hợp lệ.
        /// </summary>
        internal static string GiaTriNhapKhongHopLe {
            get {
                return ResourceManager.GetString("GiaTriNhapKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ít hơn .
        /// </summary>
        internal static string itHon {
            get {
                return ResourceManager.GetString("itHon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  không chính xác .
        /// </summary>
        internal static string khongChinhXac {
            get {
                return ResourceManager.GetString("khongChinhXac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhà ga  không được để trống..
        /// </summary>
        internal static string KhongDeTrong {
            get {
                return ResourceManager.GetString("KhongDeTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đoàn tàu không được để trống.
        /// </summary>
        internal static string KhongDeTrong1 {
            get {
                return ResourceManager.GetString("KhongDeTrong1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  không thể sửa. .
        /// </summary>
        internal static string khongTheSua {
            get {
                return ResourceManager.GetString("khongTheSua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tồn tại bất kì tuyến đường nào.
        /// </summary>
        internal static string KhongTonTaiTuyenDuong {
            get {
                return ResourceManager.GetString("KhongTonTaiTuyenDuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ký tự .
        /// </summary>
        internal static string kyTu {
            get {
                return ResourceManager.GetString("kyTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian giờ đến có xung đột thời gian với lịch trình .
        /// </summary>
        internal static string LichTrinhThoiGianGioDenXungDot {
            get {
                return ResourceManager.GetString("LichTrinhThoiGianGioDenXungDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian giờ đi có xung đột thời gian với lịch trình .
        /// </summary>
        internal static string LichTrinhThoiGianGioDiXungDot {
            get {
                return ResourceManager.GetString("LichTrinhThoiGianGioDiXungDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logout_512 {
            get {
                object obj = ResourceManager.GetObject("logout-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu đối tượng .
        /// </summary>
        internal static string LuuDoiTuong {
            get {
                return ResourceManager.GetString("LuuDoiTuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đối tượng .
        /// </summary>
        internal static string MaDoiTuong {
            get {
                return ResourceManager.GetString("MaDoiTuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã khách hàng.
        /// </summary>
        internal static string MaKH {
            get {
                return ResourceManager.GetString("MaKH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã nhân viên.
        /// </summary>
        internal static string MaNV {
            get {
                return ResourceManager.GetString("MaNV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban .
        /// </summary>
        internal static string MaPhongBan {
            get {
                return ResourceManager.GetString("MaPhongBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu nhập lại .
        /// </summary>
        internal static string MatKhauNhapLai {
            get {
                return ResourceManager.GetString("MatKhauNhapLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo .
        /// </summary>
        internal static string MCanhBao {
            get {
                return ResourceManager.GetString("MCanhBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi .
        /// </summary>
        internal static string MLoi {
            get {
                return ResourceManager.GetString("MLoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập liệu sai .
        /// </summary>
        internal static string MNhapLieuSai {
            get {
                return ResourceManager.GetString("MNhapLieuSai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công .
        /// </summary>
        internal static string MThanhCong {
            get {
                return ResourceManager.GetString("MThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thất bại .
        /// </summary>
        internal static string MThatBai {
            get {
                return ResourceManager.GetString("MThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận .
        /// </summary>
        internal static string MXacNhan {
            get {
                return ResourceManager.GetString("MXacNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  nhiều hơn .
        /// </summary>
        internal static string nhieuHon {
            get {
                return ResourceManager.GetString("nhieuHon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap no_image_available {
            get {
                object obj = ResourceManager.GetObject("no-image-available", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notes_32x32 {
            get {
                object obj = ResourceManager.GetObject("notes_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quit_exit_512 {
            get {
                object obj = ResourceManager.GetObject("quit_exit-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản .
        /// </summary>
        internal static string TaiKhoan {
            get {
                return ResourceManager.GetString("TaiKhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo đối tượng .
        /// </summary>
        internal static string TaoDoiTuong {
            get {
                return ResourceManager.GetString("TaoDoiTuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập .
        /// </summary>
        internal static string TenDangNhap {
            get {
                return ResourceManager.GetString("TenDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  thành công .
        /// </summary>
        internal static string thanhCong {
            get {
                return ResourceManager.GetString("thanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  thất bại .
        /// </summary>
        internal static string thatBai {
            get {
                return ResourceManager.GetString("thatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ticket {
            get {
                object obj = ResourceManager.GetObject("ticket", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá đối tượng .
        /// </summary>
        internal static string XoaDoiTuong {
            get {
                return ResourceManager.GetString("XoaDoiTuong", resourceCulture);
            }
        }
    }
}
