//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVeTau.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichTrinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichTrinh()
        {
            this.LichTrinh_TuyenDuong = new HashSet<LichTrinh_TuyenDuong>();
        }
    
        public string DoanTauId { get; set; }
        public System.DateTime GioChay { get; set; }
        public System.DateTime GioDen { get; set; }
        public int Id { get; set; }
        public string TenLichTrinh { get; set; }
        public bool LichTrinhMau { get; set; }
        public int TrangThai { get; set; }
    
        public virtual DoanTau DoanTau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichTrinh_TuyenDuong> LichTrinh_TuyenDuong { get; set; }
    }
}
