//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVeTau.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichTrinh_TuyenDuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichTrinh_TuyenDuong()
        {
            this.ChiTietGiaoDiches = new HashSet<ChiTietGiaoDich>();
        }
    
        public int LichTrinhId { get; set; }
        public int TuyenDuongId { get; set; }
        public int ThuTu { get; set; }
        public double ThoiGianDung { get; set; }
        public double GiaVe { get; set; }
        public bool DaChayQua { get; set; }
        public int Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietGiaoDich> ChiTietGiaoDiches { get; set; }
        public virtual LichTrinh LichTrinh { get; set; }
        public virtual TuyenDuong TuyenDuong { get; set; }
    }
}
