//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVeTau.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhongBan()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public string Id { get; set; }
        public string TenPhongBan { get; set; }
        public bool RuleChuyenTau { get; set; }
        public bool RuleNhanSu { get; set; }
        public bool RuletBanVe { get; set; }
        public bool RuleLichTrinh { get; set; }
        public bool RuleBaoCao { get; set; }
        public bool RuleQuanTri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
