//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVeTau.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuyenDuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TuyenDuong()
        {
            this.LichTrinh_TuyenDuong = new HashSet<LichTrinh_TuyenDuong>();
        }
    
        public int GaTauDauId { get; set; }
        public int GaTauCuoiId { get; set; }
        public int KhoangCach { get; set; }
        public int Id { get; set; }
    
        public virtual GaTau GaTau { get; set; }
        public virtual GaTau GaTau1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichTrinh_TuyenDuong> LichTrinh_TuyenDuong { get; set; }
    }
}
