//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVeTau.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeTauEntities : DbContext
    {
        public VeTauEntities(bool lazy)
           : base("name=VeTauEntities")
        {

            Configuration.LazyLoadingEnabled = lazy;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietGiaoDich> ChiTietGiaoDiches { get; set; }
        public virtual DbSet<DoanTau> DoanTaus { get; set; }
        public virtual DbSet<DoanTau_LoaiGhe> DoanTau_LoaiGhe { get; set; }
        public virtual DbSet<GaTau> GaTaus { get; set; }
        public virtual DbSet<GiaoDich> GiaoDiches { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LichTrinh> LichTrinhs { get; set; }
        public virtual DbSet<LichTrinh_TuyenDuong> LichTrinh_TuyenDuong { get; set; }
        public virtual DbSet<LoaiGhe> LoaiGhes { get; set; }
        public virtual DbSet<LoaiKhachHang> LoaiKhachHangs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TuyenDuong> TuyenDuongs { get; set; }
    }
}
