using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using BanVeTau.DAL;

namespace BanVeTau.GUI
{
    public partial class UcRNhanVien : UserControl
    {
        public UcRNhanVien()
        {
            InitializeComponent();
            Dock = DockStyle.Fill;
            chartControl1.DataSource = BaoCaoDal.LayGiaoDichNhanVien();
            chartControl1.RefreshData();
            // This line of code is generated by Data Source Configuration Wizard
           
        }
    }
}
